# Generated by Django 5.2.12 on 2026-03-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('affiliation', models.CharField(blank=True, max_length=120)),
                ('homeland', models.CharField(blank=True, max_length=120)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('element', models.CharField(blank=True, max_length=80)),
                ('first_appearance', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='characters/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainsite.character')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
