# Generated by Django 5.2.12 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_character_characterimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', '男生'), ('female', '女生')], max_length=6),
        ),
    ]
